### ISSUE TITLE
Exit code 3

### ISSUE THREAD

**Issue by BigTexasDork** [prowler-cloud/prowler#629] opened 2020-06-26 18:57 UTC
I'm getting an non-zero exit code (3) which is messing up my automation.  Is the `exit 3` a true error?

I've narrowed it down to group4.

Running with this command:
`bash -x ./prowler -g group4 -M html 2>stderr.txt`

the end of the stderr.txt file has this (i can paste more if needed):
```+ echo '<td>4.4</td>'
+ echo '<td>[check44]' Ensure routing tables for VPC peering are '"least' 'access"' '(Not' 'Scored)</td>'
+ echo '<td>us-west-2:' No VPC peering 'found</td>'
+ echo '</tr>'
+ [[ PASS == \F\A\I\L ]]
+ [[ PASS == \W\A\R\N\I\N\G ]]
+ is_junit_output_enabled
+ [[  html  =~  junit-xml  ]]
+ false
+ for i in '"${!GROUP_ID[@]}"'
+ '[' cislevel1 == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' cislevel2 == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' extras == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' forensics-ready == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' gdpr == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' hipaa == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' secrets == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' apigateway == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' rds == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' elasticsearch == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' pci == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' trustboundaries == group4 ']'
+ for i in '"${!GROUP_ID[@]}"'
+ '[' internet-exposed == group4 ']'
+ [[ html =~ html ]]
+ addHtmlFooter
+ cat
+ unset HTML_REPORT_INIT
+ cleanTemp
+ [[ 0 -ne 1 ]]
+ rm -fr /tmp/prowler.cred_report-XDV1r5
+ scoring
+ [[ '' == \1 ]]
+ exit 3
+ cleanTemp
+ [[ 0 -ne 1 ]]
+ rm -fr /tmp/prowler.cred_report-XDV1r5```

**Comment by amanludhwaniatgithub** [comment] 2020-07-27 12:27
The Same issue I am also facing is there any update for the issue

**Comment by toniblyx** [comment] 2020-07-30 21:51
Thank you both for your patience here. I need to take some time on this to understand how to improve it.

**Comment by marcjay** [comment] 2020-08-07 20:28
Is there definitely an issue here? I was trying to reproduce this and whilst I did get exit code 3, it was because check43 (not included in the output above) was failing. This check would fail on any AWS account out of the box: "[check43] Ensure the default security group of every VPC restricts all traffic (Scored)" - the default Security Group allows outbound traffic to 0.0.0.0

Once I fixed that default SG, re-running group4 with the command above exited with 0. Is there a chance that your check43 is failing too? No doubt I'm missing something though

**Comment by deanvaturi** [comment] 2020-10-13 08:42
Hi, any updates regarding this issue? as the job is successful but I am getting error code 3

**Comment by toniblyx** [comment] 2020-10-15 21:29
Hi @deanvaturi can you please share here the command that you are using and output? As @marcjay mentioned, Prowler shows exit code 3 when a check fails because users want their deployment fails and make sure no insecure resources are deployed (when using codebuild, jenkins, etc.), see this line here:
https://github.com/toniblyx/prowler/blob/master/include/outputs#L133

So for example try running prowler with a check that pass and right afterwards run `echo $?` and you will get a 0. If you do the same with a check that ends with a fail `echo $?` will give you a 3.

In order to change that behavior you have two options, a dirty one changing that mentioned line or a nicer one with something like this in your build (this is just an example):
`SCAN_RESULT=$(./prowler -c check32 -M csv,html && echo OK || echo FAILED)`
That will make CodeBuild to work fine any time and also you will capture the output in that variable, in case the proper prowler command fails then CodeBuild will fail. Does it make sense?

**Comment by Kirizan** [comment] 2021-09-07 13:01
I added PR #865 to control if failed Checks generate exit code 3.

**Comment by toniblyx** [comment] 2021-09-23 08:22
This is finally fixed with the Z feature thanks to @Kirizan. Please test branch 2.5.1 and reopen this issue if needed.

**Closed as completed by toniblyx** 2021-09-23 08:22 UTC
