### ISSUE TITLE
Group 3 checks incorrectly reporting as Failed

### ISSUE THREAD

**Issue by RyanBeatty** [prowler-cloud/prowler#289] opened 2019-02-03 20:21 UTC
I've noticed that some checks in group 3 (specifically check31, check32, check35, check36, check38, check39) were reporting as being failed, when I can clearly see that I have both metrics and alarms satisfying those checks in my AWS Console

I believe the issue is that most of these checks seem to use `grep` + `awk` on text output from the aws cli to find metrics that satisfy the checks instead of using the aws cli --query option more. Using check 31 as an example:

`METRICFILTER_SET` gets populated by [this command](https://github.com/toniblyx/prowler/blob/master/checks/check31#L26). When I run this manually, it just returns the empty string even though I have metrics that check for `UnauthorizedOperation` and `AccessDenied` events. I think a more robust solution for these checks would be to take more advantage of the aws cli [--query](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter) option with something like the following (for check31):
```
$ aws logs describe-metric-filters --log-group-name <my-log-group-name> --query 'metricFilters[?contains(filterPattern, `UnauthorizedOperation`) == `true` && contains(filterPattern, `AccessDenied`) == `true`].metricTransformations[*].metricName' --output text
```

This correctly prints out the metric name for my metric that satisfies check31

**Comment by rniedzial** [comment] 2019-02-05 23:54
The issue is that the current checks look for a metric filter using a pattern, and then the check looks for alarms with names from another pattern. If your alarm name doesn't match that pattern the check fails.

So as you pointed out the checks are not using the AWS CLI commands to get this information, its pretty arbitrary.

This whole group of filters ought to be reduced to a single method that takes in some arguments, because they are just clones. I am no bash expert, but I did re-write check34 as a quick test. If we write a metricCheck method and just pass in the value of what I have here as METRIC_GREP, this code ought to be re-usable for all of these (check31...39, check 310..314).

https://gist.github.com/rniedzial/29ba8c3054720dfb8d6775bb79f8080b

**Comment by toniblyx** [comment] 2019-02-06 00:44
Thanks for your comments @RyanBeatty and @rniedzial, you are right. Actually I think these checks are pretty arbitrary because you might have other ways to check them up. I agree with your filter option is more accurate than my grep+awk implementation, by that time I didn't use `--query` as I can do it now.

I'm gonna look in detail to your both recommendations as soon as I can, and see what is the best option. @rniedzial please, feel free to send a PR if you consider that your test is a good candidate for these checks.
Thanks again!

**Comment by rniedzial** [comment] 2019-02-06 01:08
Done. https://github.com/toniblyx/prowler/pull/292

**Comment by toniblyx** [comment] 2019-02-06 01:12
Awesome @rniedzial!! Please give me some time to review and test your new alternatives. I appreciate your help!

**Comment by toniblyx** [comment] 2019-02-21 02:51
@rniedzial just reviewed it and asked you some changes in case you can. Thanks!

**Comment by toniblyx** [comment] 2019-05-16 01:58
We are discussing this issue in #325 so I'll close this one as duplicated

**Closed as completed by toniblyx** 2019-05-16 01:58 UTC
