### ISSUE TITLE
Docker task running Prowler cannot find ./output/prowler-output-./include/whoami

### ISSUE THREAD

**Issue by AmyGreaves** [prowler-cloud/prowler#797] opened 2021-05-12 17:34 UTC
I'm running prowler scans in an ECS container. My local copy of prowler can pick-up the whoami file but the task cannot. 

The outputted csv file has './include/whoami: line 47: jq: command not found' in the ACCOUNT_NUM field and the task outputs an 'tee: './output/prowler-output-./include/whoami:': No such file or directory' error message for every check.

I can provide the dockerfile used to replicate if helpful, thanks.

**Comment by FishermansEnemy** [comment] 2021-05-18 09:04
I had this same issue. I was running Kali linux and the error was caused by not having the jq command installed as standard.

**Comment by toniblyx** [comment] 2021-05-18 10:20
As @FishermansEnemy says, that seems to me that jq is not installed in the image instead of an issue with include/whoami. Are you using the official image (toniblyx/prowler:latest) or building your own with the existing Dockerfile https://github.com/toniblyx/prowler/blob/master/util/Dockerfile? You can see here all dependencies https://github.com/toniblyx/prowler/blob/583cffaefb067e8fbd81a5300db11a0a841102b2/util/Dockerfile#L8-L10

**Comment by toniblyx** [comment] 2021-11-04 18:14
Closing it. There are no further comments in this issue.

**Closed as completed by toniblyx** 2021-11-04 18:14 UTC
