### ISSUE TITLE
-E flag not working anymore with Macie commit

### ISSUE THREAD

**Issue by chbiel** [prowler-cloud/prowler#564] opened 2020-04-21 10:14 UTC
We call prowler like
```
prowler -r eu-central-1 -f eu-central-1 -s -E check14,check26,check114,check120
```

The commit https://github.com/toniblyx/prowler/commit/0c7805356ee896879d2b16df22fe64c4cde87360 breaks this, as before that commit the checks where correctly excluded.
Now after that commit the checks are not excluded anymore.

I found the following error message as the only difference in the output before the checks:
```
An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded
```
The reason will be, that "Macie" is not available in eu yet: https://aws.amazon.com/de/about-aws/global-infrastructure/regional-product-services/

Therefor, when calling 
```
aws macie list-member-accounts --region eu-central1 --output text --query 'memberAccounts[*]'
``` 
results in an 
`Could not connect to the endpoint URL: "https://macie.eu-central1.amazonaws.com/"`-error

I see that the commit checks for that error message, but for some reason something still seems to be wrong.

If more info is needed please tell me how I can support

**Comment by toniblyx** [comment] 2020-04-21 11:06
Can you share the output error or is only that endpoint error?

**Comment by chbiel** [comment] 2020-04-21 14:22
This is were the Throtteling error comes from:
```
1.0 Identity and Access Management - CIS only - [group1] ***********  

 0.1 Generating AWS IAM Credential Report...  

An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded

 1.1  [check11] Avoid the use of the root account (Scored) 
       PASS! Root user in the account wasn't accessed in the last 1 days
```
There is nothing more. So it seems that the error comes out of the `Generating AWS IAM Credential Report...`, but I don't see the relation between that commit and the error.
After that the checks get executed but without applying the -E option


Complete output from the test command:
```
~ aws macie list-member-accounts --region eu-central1 --output text --query 'memberAccounts[*]'

Could not connect to the endpoint URL: "https://macie.eu-central1.amazonaws.com/"
```

**Comment by toniblyx** [comment] 2020-04-21 15:05
That throttling error is not created directly from prowler unless you run it multiple times at the same time or continuously since it tries to create a credentials report because you invoke check14. So weird, can you confirm that if you roll back that change in  checks/check_extra712  works fine again?

**Comment by marcjay** [comment] 2020-04-21 17:03
I can reproduce this too:
`aws macie list-member-accounts --region eu-west-1`
Hangs for a while and eventually returns
`Connect timeout on endpoint URL: "https://macie.eu-west-1.amazonaws.com/"`
I think a different approach is needed to check if Macie is available here - just the fact it hangs for a while slows down Prowler runs unnecessarily
https://github.com/toniblyx/prowler/blob/master/checks/check_extra712#L24

**Comment by chbiel** [comment] 2020-04-21 18:54
> That throttling error is not created directly from prowler unless you run it multiple times at the same time or continuously since it tries to create a credentials report because you invoke check14. So weird, can you confirm that if you roll back that change in checks/check_extra712 works fine again?

yes, https://github.com/toniblyx/prowler/commit/0c7805356ee896879d2b16df22fe64c4cde87360 is not OK.

Previous commit https://github.com/toniblyx/prowler/commit/86ea46d77cebccffbc6fc0d963a9ad70540dbc28 is OK

**Comment by toniblyx** [comment] 2020-04-22 08:43
I have rolled back that issue with Macie but I think we are mixing two things here.
1) `-E` is not working, that could be related to the recent changes on listing checks and groups, @marcjay that was working before those changes. I can confirm -E (exclude checks) is not working now.
2) Macie gives an error due to the endpoint, that has been fixed with rollback.

**Comment by marcjay** [comment] 2020-04-22 08:47
@toniblyx ah, would you like me to look at the -E issue as I likely caused it?

**Comment by marcjay** [comment] 2020-04-22 09:03
See #567 for a PR to fix the `-E` flag issue  - sorry for the inconvenience @chbiel

**Comment by chbiel** [comment] 2020-04-22 09:36
Thank you.

Sorry for mixing that up but it looked like the Macie thing introduced the "-E" bug :)

**Comment by toniblyx** [comment] 2020-04-22 09:56
Thanks @marcjay for your quick answer and @chbiel for the heads up!

**Closed as completed by toniblyx** 2020-04-22 09:56 UTC
