### ISSUE TITLE
Credential renewal broke on Alpine Linux

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#775] opened 2021-04-12 17:43 UTC
@toniblyx I think https://github.com/toniblyx/prowler/pull/773 broke AWS credential renewal on Alpine Linux, I'm digging through to see if I can find the exact lines. I think the issue we keep running into is that the OS supplied date command is very non-standard so the parameters and formats accepted differ significantly between platforms. I'll know more as soon as I track down where the errors are coming from.

**Comment by zfLQ2qx2** [comment] 2021-04-12 18:13
@toniblyx Output from Alpine date command is:

date -u -d 2021-04-12T18:51:21Z +%s
date: invalid date '2021-04-12T18:51:21Z'

Looks like the format it accepts are:
	hh:mm[:ss]
	[YYYY.]MM.DD-hh:mm[:ss]
	YYYY-MM-DD hh:mm[:ss]
	[[[[[YY]YY]MM]DD]hh]mm[.ss]

And 2021-04-12T18:51:21Z appears to be output from expiration parameter returned by aws sts assume-role.

If you look back at https://github.com/toniblyx/prowler/pull/736 one potential workaround is this:

export AWS_SESSION_EXPIRATION=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration | fromdateiso8601')

Which looks like it was merged at some point, not sure when it got backed out, but if you run this test case:

echo '{ "Credentials": { "Expiration": "2021-04-12T18:51:21Z" } }' | jq -r '.Credentials.Expiration | fromdateiso8601'

It returns the epoch time which is what this line is trying to do - https://github.com/toniblyx/prowler/blob/master/include/os_detector#L115

So changing https://github.com/toniblyx/prowler/blob/master/include/assume_role#L73 to:
export AWS_SESSION_EXPIRATION=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration | fromdateiso8601')

Avoids that convert_date_to_timestamp function altogether - though as far as I remember this is the only place where that function is used.

I see that you added a sed to remove /+00:00/ from that jq returns, is there a platform that uses that as a suffix instead of 'Z'? I think we could search and replace that in jq if we have output that fromdateiso8601 can't parse.

@toniblyx Looks like that one line change was all that was needed to make it work on Alpine. Passing AWS credentials to Prowler via environment doesn't work anymore - probably being cleared by assumerole, I can work around it by running aws configure on my test container. I'll raise a PR with the one line fix and detection for missing credentials I hit. If you need me to customize it to replace '+00:00' with 'Z' for the time stamp parsing, if its an issue, please let me know.

**Comment by toniblyx** [comment] 2021-04-12 19:22
Thanks @zfLQ2qx2. Ok, after some more debugging and testing aws-cli v1 vs v2 in both mac and linux, I have realized that  the issue is the data output differences between versions... Command `aw sts assume-role` outputs:
- this `2021-04-12T19:36:05+00:00` in aws-cli/2.1.31
- this `2021-04-12T19:35:59Z` in aws-cli/1.19.49

So the output has to be sanitized to something like `YYY-MM-DDTHH:MM:SS` before parsing. I have added something like this `sed 's/+00:00//g;s/Z//g'` and makes the trick. I'm pushing it to branch 2.4.1 in a minute.

**Comment by toniblyx** [comment] 2021-04-12 19:26
Docker image toniblyx/prowler:2.4.1 is being built but in any case you can test it manually if you want.

**Comment by zfLQ2qx2** [comment] 2021-04-12 20:10
@toniblyx There we go. aws cli v2 isn't backwards compatible with v1, a lot of the commands work the same way but there are enough differences you basically have to go and test everything. I know that Alpine Linux is holding at aws-cli 1.18 for now for just that reason. I looked at building v2 locally and just reading the differences I could tell it was going to make a lot of work for me, opted for 1.19 instead.

**Comment by toniblyx** [comment] 2021-04-12 20:39
As far as I have seen in other places, Alpine is not compatible with aws-cli v2 so far.  Other option is to use amazonlinux container, both prowler and amazonlinux are same size 163MB.

So let's leave it as it is now in 2.4.1 if it works. Let me know if we can close this issue. Thanks!!

**Comment by zfLQ2qx2** [comment] 2021-04-13 01:19
Will test tomorrow, I did a local patch for tonight’s run.

**Comment by zfLQ2qx2** [comment] 2021-04-13 19:11
@toniblyx Verified that the fix doesn't resolve the issue, 2021-04-13T20:00:15 isn't one of the formats that the date command accepts:

hh:mm[:ss]
[YYYY.]MM.DD-hh:mm[:ss]
YYYY-MM-DD hh:mm[:ss]
[[[[[YY]YY]MM]DD]hh]mm[.ss]

If you are open to further consideration of the jq solution, here is one that passes both test cases:

```
echo '{ "Credentials": { "Expiration": "2021-04-12T18:51:21Z" } }' | jq -r '.Credentials.Expiration | sub("\\+00:00";"Z") | fromdateiso8601'

echo '{ "Credentials": { "Expiration": "2021-04-12T18:51:21+00:00" } }' | jq -r '.Credentials.Expiration | sub("\\+00:00";"Z") | fromdateiso8601'
```

So the fix becomes:

```
export AWS_SESSION_EXPIRATION=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration | sub("\\+00:00";"Z") | fromdateiso8601')
```

Advantage of moving the date calculation to jq is that is avoids all the platform differences in the date command and it also avoids executing several shell commands in a function that is called relatively frequently.

**Comment by toniblyx** [comment] 2021-04-14 09:48
Thanks! Now it should be fine. Pushed to 2.4.1 branch.

**Comment by zfLQ2qx2** [comment] 2021-04-14 13:44
Awesome!!

**Closed as completed** 2021-04-14 13:44 UTC
